name: Playwright Tests
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
env:
    VITE_API_KEY: ${{ vars.VITE_API_KEY }}
    VITE_AUTH_DOMAIN: ${{ vars.VITE_AUTH_DOMAIN }}
    VITE_DATABASE_URL: ${{ vars.VITE_DATABASE_URL }}
    VITE_PROJECT_ID: ${{ vars.VITE_PROJECT_ID }}
    VITE_STORAGE_BUCKET: ${{ vars.VITE_STORAGE_BUCKET }}
    VITE_MESSAGING_SENDER_ID: ${{ vars.VITE_MESSAGING_SENDER_ID }}
    VITE_APP_ID: ${{ vars.VITE_APP_ID }}
    VITE_MEASUREMENT_ID: ${{ vars.VITE_MEASUREMENT_ID }}
    VITE_STORAGE_URL_PREFIX: ${{ vars.VITE_STORAGE_URL_PREFIX }}
    VITE_EMAIL_NAME: ${{ vars.VITE_EMAIL_NAME }}

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Install Playwright Browsers
              run: pnpm dlx playwright install --with-deps
            - name: Run Playwright tests
              run: pnpm dlx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
