name: Integration Tests
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
jobs:
    integration-tests:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        env:
            VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
            VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
            VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
            VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
            VITE_AUTH_DOMAIN: ${{ vars.VITE_AUTH_DOMAIN }}
            VITE_DATABASE_URL: ${{ vars.VITE_DATABASE_URL }}
            VITE_PROJECT_ID: ${{ vars.VITE_PROJECT_ID }}
            VITE_STORAGE_BUCKET: ${{ vars.VITE_STORAGE_BUCKET }}
            VITE_STORAGE_URL_PREFIX: ${{ vars.VITE_STORAGE_URL_PREFIX }}
            VITE_EMAIL_NAME: ${{ vars.VITE_EMAIL_NAME }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  cache-name: cache-node-modules
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-
                  cache-name: cache-pnpm-lock
            - name: Install dependencies
              run: pnpm install
            - name: Install Playwright Browsers
              run: pnpm dlx playwright install --with-deps
            - name: Run Playwright tests
              run: |
                  echo "$VITE_AUTH_DOMAIN"
                  echo "finished testing"
                  pnpm dlx playwright test
            - name: Saving tests results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
